name: 'Mobile App Release'
description: 'Releases mobile apps to Apple App Store and Google Play Store'

inputs:
  branch:
    description: 'The Expo branch used for OTA update releases'
    default: 'production'
    required: false
  commit-author-email:
    description: 'The email address of the commit author'
    default: ''
    required: false
  commit-author-name:
    description: 'The name of the commit author'
    default: ''
    required: false
  expo-token:
    description: 'The token for the expo account being released from'
    required: true
  expo-app-specific-password:
    description: 'The app-specific password used to submit a build to the Apple App Store'
    required: true
  git-token:
    description: 'The token to access private repos'
    default: ''
    required: false
  increment-build-number:
    description: 'true if the script should automatically increment the build number in an `app.config.[jt]s`'
    default: 'true'
    required: false
  platform:
    description: 'Which platform to build for (all|android|ios)'
    required: false
    default: 'all'
  profile:
    description: 'What profile from `eas.json` to use'
    required: false
    default: 'production'
  release-channel:
    description: 'Channel to use in the EAS Update'
    default: 'production'
    required: false
  release-message:
    description: 'Message to use in the EAS Update'
    default: 'Release'
    required: false
  submodules:
    description: 'Whether to checkout submodules'
    default: 'true'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Login to Expo
      uses: expo/expo-github-action@v6
      with:
        eas-version: latest
        expo-version: latest
        token: ${{ inputs.expo-token }}

    - name: Increment Build Number
      if: ${{ inputs.increment-build-number != 'false' }}
      shell: bash
      run: |
        if [ -f "app.config.ts" ]; then
          if hash python3 2>/dev/null; then
            # Run `python3` if it exists
            python3 ${{ github.action_path }}/auto-increment.py app.config.ts
          else
            # Default to `python`
            python ${{ github.action_path }}/auto-increment.py app.config.ts
          fi
        elif [ -f "app.config.js" ]; then
          if hash python3 2>/dev/null; then
            python3 ${{ github.action_path }}/auto-increment.py app.config.js
          else
            python ${{ github.action_path }}/auto-increment.py app.config.js
          fi
        fi
        git config user.email ${{ inputs.commit-author-email }}
        git config user.name ${{ inputs.commit-author-name }}
        git add app.config.*
        git commit --no-verify -m 'Increment build number'
        git push

    - name: Publish
      run: eas update --branch="${{ inputs.release-channel }}" --non-interactive --message="${{ inputs.release-message }}"
      shell: bash

    - name: Build
      run: |
        eas build --platform="${{ inputs.platform }}" --clear-cache --non-interactive --no-wait --auto-submit --profile="${{ inputs.profile }}"
      shell: bash
      env:
        EXPO_APPLE_APP_SPECIFIC_PASSWORD: ${{ inputs.expo-app-specific-password }}

    - uses: dmsi-io/gha-back-merge@main
      if: inputs.git-token != ''
      with:
        commit-author-email: ${{ inputs.commit-author-email }}
        commit-author-name: ${{ inputs.commit-author-name }}
        submodules: ${{ inputs.submodules }}
        token: ${{ inputs.git-token }}
